### PR TITLE
Update README formatting

### PR DESCRIPTION
**Pull request by sjyoung12**
Convert numbered lists to sub-headings for better readability.

Before | After
-- | --
image | image

### CODE REVIEW

**Comment by sjyoung12** [comment]
@danReynolds : thoughts on removing the `<details>` formatting around the "Why does this exist" and "FAQs" sections, and adding a table of contents?

**Comment by danReynolds** [comment]
@sjyoung12 Like in the repo wiki https://github.com/NerdWalletOSS/apollo-invalidation-policies/wiki ? Or something else? Wiki entries my concern would be people just look at the primary README and don't often go to wikis for smaller projects like this, but I could be wrong.

**Comment by sjyoung12** [comment]
@danReynolds : I was referring to these sections of the main repo README:
image

IMO, that would make the README easier to navigate.  Not a strong opinion, just a thought. 🙂

**Comment by danReynolds** [comment]
lgtm!

**Pull request merged**
